// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"kv-store/internal/adapter/handler"
	"kv-store/internal/adapter/protocol"
	"kv-store/internal/infrastructure/persistence"
	"kv-store/internal/infrastructure/storage"
	"kv-store/internal/usecase"
)

// Injectors from wire.go:

func InitializeContainer(opt persistence.AOFProviderOption) (*Container, error) {
	keyValueRepository := storage.NewStore()
	persistencxeRepository, err := persistence.NewAOFProvider(opt)
	if err != nil {
		return nil, err
	}
	stats := usecase.NewStats(keyValueRepository)
	parser := protocol.NewParser()
	commandHandler := usecase.NewCommandHadler(keyValueRepository, persistencxeRepository, stats, parser)
	tcpHandler := handler.NewTCPHandler(commandHandler, parser)
	container := NewContainer(keyValueRepository, persistencxeRepository, commandHandler, tcpHandler, parser)
	return container, nil
}
